# Generated by Django 4.1.1 on 2022-09-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('project', models.TextField()),
                ('reporter', models.TextField()),
                ('assignee', models.TextField()),
                ('status', models.TextField()),
                ('created_at', models.DateField()),
                ('closed_at', models.DateField()),
                ('comment', models.TextField()),
                ('watcher', models.TextField()),
                ('label', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('title', models.TextField()),
                ('creator', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
