# Generated by Django 4.1.1 on 2022-09-15 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_issues_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
